GOOGLE_API_KEY = "AIzaSyCdIVAUbiuLFp-JgZ5nUZhGVppS6I7ZGJI"
MONTHLY_BUDGET = 15000

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1SFnUCyE-cZGONpd9MKrvG3_M8QJPjxbHGz3UnARSQAc/edit?usp=sharing"
type = "service_account"
project_id = "eatficiency-project"
private_key_id = "7d35af6b6f850013d69dfdce170b72e16ce135b8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDm7MPQbW4JUDuP
mFkTzf2Boc9tlk/+1bKB049PmrvCCXPfwd1SlL1M9FyP3RVMtvxAFy5UWF8m+vep
k5Ls6zTiB02+33fMnkU9nvFJSuo79y6DKsbnqhQBxMK0IHFBji9OzeDUiiCW+Rfj
1tVHJjCTtRynOFrScLFiGZEQgIFRaneEDLVKo5MJTbr+tCQHfRUs+EmyaxsHY2AQ
NiNZsWKLIF1hxGVP8jyp7HDAjfwN+wkmKMwi/3PAuBBthJePGww+kdAWR0hY1vOj
qN1KDOOlLYAX0o9d5BGRNUHh0oF7lJdcmX8ezTS986yGGG48esF29z1xhMBTLx+d
r8MXmgWbAgMBAAECggEAM8muYmxgLIuHR/1RIM1mCG/q7ncyyoJPTalN7vrTF8F5
8JjwEyiTSZJVvdfFgpZY/OCV/clx0XKgHzIe1a4sBnK/30oLemKWQasHDrpTzI3z
KuxpfiPY58qiJbZO3/ZMqr4mKVQu2dzUHD8eRp4Mb9vCqMfNKnumdEsqispe9gxe
0D/ldC1MMO/b/kLforwRXKDszt821gyQBrILzPUtqyn+MtN5RwsZXL5i5MWb4nhf
CrF/dSpYoZLX5hYWGjGLtzWvC0KymANQGvX9QLcoZywyac88i5+wtVQkWYNQ35ms
h5T8VvSpr/psHl3Uoan2X6zBj1R5q2OFnuryCe0S5QKBgQD79surTLyBiOzZ3cHF
pVF30itP5uxqRvyIqMW74fz7SOPZP/wFyiDycorBCsBYWTv1a99IfR1lPprKkIQR
D6ytHPmwluzZ4JQhRwhDU3xV4uUFaKXRMJxEUx4MNKt5A7x69ce9GqJj8O3WDCYO
XdBpYRpw+3bH9cvfTgOeagKbrwKBgQDqn7Isc6/dUm3W7auyfiYS90CSKWl2i4OS
LAiyqSVWyLwdEr9/NKS4FSjkj+bd2rr+Co6XU9AsCHWS1ZdKq8iHRDJauCqUC5eZ
921zL/DdNrhhFG5pNvO4OAF11SZdTboQELasowTKMDUQmE6esAk1zfWCuInG3Yuk
qmj0UceT1QKBgQD5B9YJOtDdnn2qX5lTRbAdo2YXlP95kyupzlWQ+y1VF5fLc4ge
GMczma42We/94kR2ruWC+dYB6TyIlQlS65EZkJfgx2rVdTgzI8ew82TiZl1BWUr6
VPc+OIBsQ+pusxio1x9Rcm+qI8iOVHeQn3yLiuPdY0zlGbUkwjClc9WcFQKBgQC0
azE79YobCzPjvsf1bgQhOXix7J5oxkfas3nMyT0pSxs80Bnp27V+yOa1O+MwXu7E
Q6H6xDykX6zpyM2aYhbFza9bC5vSVEez4gyMMyVpNpb6MBfnWJZ55rdYwRvLS+X0
TKXsgz8/q2pi5HwwkvXCJirQ5s8r2Vl0uoYSuoBaMQKBgQC0AVRCraIV1Mrepe40
Z/tt1LP6dBVIbgTkrUiiAzgS1cjardj1FEIeCuHSfCrDS5oAO/VVHja5p/OgRzj5
wIkIov1xGH26tMA3I/UY4gTiDAyAlPz/lZzMgFtN4pEYAyykjK7kQrHb6wxxCCFd
WAIV5zhO0HnpQqInk9aQHTS2kw==
-----END PRIVATE KEY-----
"""
client_email = "eatficiencyqa@eatficiency-project.iam.gserviceaccount.com"
client_id = "107241709977973551929"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/eatficiencyqa%40eatficiency-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"